services:
  mysql:
    image: mysql:8.0
    container_name: mysql_user_container
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: studentdb
      MYSQL_USER: studentuser
      MYSQL_PASSWORD: studentpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql

volumes:
  mysql_user_data:
